# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import comm_pb2 as comm__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in comm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushIntermediateTensors = channel.unary_unary(
                '/CommService/PushIntermediateTensors',
                request_serializer=comm__pb2.GrpcRequestData.SerializeToString,
                response_deserializer=comm__pb2.GrpcResponseData.FromString,
                _registered_method=True)
        self.PushSamplerOutput = channel.unary_unary(
                '/CommService/PushSamplerOutput',
                request_serializer=comm__pb2.SamplerOutput.SerializeToString,
                response_deserializer=comm__pb2.GrpcResponseData.FromString,
                _registered_method=True)
        self.ExecutingWorkerStep = channel.unary_unary(
                '/CommService/ExecutingWorkerStep',
                request_serializer=comm__pb2.GrpcTriggerRequest.SerializeToString,
                response_deserializer=comm__pb2.GrpcResponseData.FromString,
                _registered_method=True)
        self.JoinPipeline = channel.unary_unary(
                '/CommService/JoinPipeline',
                request_serializer=comm__pb2.NodeInfo.SerializeToString,
                response_deserializer=comm__pb2.GrpcResponseData.FromString,
                _registered_method=True)


class CommServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushIntermediateTensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushSamplerOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutingWorkerStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushIntermediateTensors': grpc.unary_unary_rpc_method_handler(
                    servicer.PushIntermediateTensors,
                    request_deserializer=comm__pb2.GrpcRequestData.FromString,
                    response_serializer=comm__pb2.GrpcResponseData.SerializeToString,
            ),
            'PushSamplerOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.PushSamplerOutput,
                    request_deserializer=comm__pb2.SamplerOutput.FromString,
                    response_serializer=comm__pb2.GrpcResponseData.SerializeToString,
            ),
            'ExecutingWorkerStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutingWorkerStep,
                    request_deserializer=comm__pb2.GrpcTriggerRequest.FromString,
                    response_serializer=comm__pb2.GrpcResponseData.SerializeToString,
            ),
            'JoinPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinPipeline,
                    request_deserializer=comm__pb2.NodeInfo.FromString,
                    response_serializer=comm__pb2.GrpcResponseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CommService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushIntermediateTensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommService/PushIntermediateTensors',
            comm__pb2.GrpcRequestData.SerializeToString,
            comm__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushSamplerOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommService/PushSamplerOutput',
            comm__pb2.SamplerOutput.SerializeToString,
            comm__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutingWorkerStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommService/ExecutingWorkerStep',
            comm__pb2.GrpcTriggerRequest.SerializeToString,
            comm__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CommService/JoinPipeline',
            comm__pb2.NodeInfo.SerializeToString,
            comm__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
