# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comm.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\"/\n\x0bTensorEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\x0btensor_data\x18\x02 \x01(\x0c\"4\n\x13IntermediateTensors\x12\x1d\n\x07tensors\x18\x01 \x03(\x0b\x32\x0c.TensorEntry\"\x93\x01\n\x0fGrpcRequestData\x12\x1d\n\x15\x65xecute_model_request\x18\x01 \x01(\x0c\x12\x32\n\x14intermediate_tensors\x18\x02 \x01(\x0b\x32\x14.IntermediateTensors\x12\x15\n\rgrpc_metadata\x18\x03 \x01(\x0c\x12\x16\n\x0evirtual_engine\x18\x04 \x01(\x05\"<\n\rSamplerOutput\x12\x13\n\x0boutput_data\x18\x01 \x01(\x0c\x12\x16\n\x0evirtual_engine\x18\x02 \x01(\x05\"\x1f\n\x10GrpcResponseData\x12\x0b\n\x03res\x18\x01 \x01(\x05\",\n\x12GrpcTriggerRequest\x12\x16\n\x0evirtual_engine\x18\x01 \x01(\x05\">\n\x08NodeInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x13\n\x0bstart_layer\x18\x02 \x01(\x05\x12\x11\n\tend_layer\x18\x03 \x01(\x05\x32\xfa\x01\n\x0b\x43ommService\x12@\n\x17PushIntermediateTensors\x12\x10.GrpcRequestData\x1a\x11.GrpcResponseData\"\x00\x12\x38\n\x11PushSamplerOutput\x12\x0e.SamplerOutput\x1a\x11.GrpcResponseData\"\x00\x12?\n\x13\x45xecutingWorkerStep\x12\x13.GrpcTriggerRequest\x1a\x11.GrpcResponseData\"\x00\x12.\n\x0cJoinPipeline\x12\t.NodeInfo\x1a\x11.GrpcResponseData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORENTRY']._serialized_start=14
  _globals['_TENSORENTRY']._serialized_end=61
  _globals['_INTERMEDIATETENSORS']._serialized_start=63
  _globals['_INTERMEDIATETENSORS']._serialized_end=115
  _globals['_GRPCREQUESTDATA']._serialized_start=118
  _globals['_GRPCREQUESTDATA']._serialized_end=265
  _globals['_SAMPLEROUTPUT']._serialized_start=267
  _globals['_SAMPLEROUTPUT']._serialized_end=327
  _globals['_GRPCRESPONSEDATA']._serialized_start=329
  _globals['_GRPCRESPONSEDATA']._serialized_end=360
  _globals['_GRPCTRIGGERREQUEST']._serialized_start=362
  _globals['_GRPCTRIGGERREQUEST']._serialized_end=406
  _globals['_NODEINFO']._serialized_start=408
  _globals['_NODEINFO']._serialized_end=470
  _globals['_COMMSERVICE']._serialized_start=473
  _globals['_COMMSERVICE']._serialized_end=723
# @@protoc_insertion_point(module_scope)
